### ISSUE TITLE
Calculall 4.0.1 quickfixes

### ISSUE THREAD

**Issue by AlstonLin** [AlstonLin/Calculall#15]
A few problems with the current release needs urgent fixes

- minSdkVersion is set to 19 (Kitkat) but we now use features that require 21 (Lollipop), so we need to bump that number (we'll have multiple APKs so that we can serve phones with API level 14  - 21 the older Calculall 3.0)

- All text in the buttons are capitalized (including greek letters for some reason). Definitely must fix this

- Decomp menu text (in Matrix mode) should have their font colors match their themes (Orange on Black theme causes the text to be hard to read)

**Comment by davidlky** [comment]
done!
